apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      volumes:
        - name: app-volume-dev
      persistenVolumeClaim:
        claimName: app-claim-volume-dev
      containers:
      - name: postgres-database-container
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
            secretKeyRef:
            - name: postgres-secrets
            type: Opaque
            data:
            - password: QmVsZ3JhZGUK
