apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume-dev
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
  path: "/mnt/data"  
 
